### ISSUE TITLE
Possibility to cancel pending orders if Take profit is reached first

### ISSUE THREAD

**Issue by eduardomendes9209** [EarnForex/PositionSizer#101]
![image](https://github.com/user-attachments/assets/bd5d9ee9-f5e9-4f7f-aadc-efe9ecf2166d)
Is it possible to create a function that cancel the pending orders if price hit a certain price level. example hit tp target before activating the order. then pending orders will be cancelled automatically.

**Comment by EarnForex** [comment]
Hello!

I don't think I will ever add anything like that to the Position Sizer, but you can use the Account Protector on a separate chart to achieve the same:
https://www.earnforex.com/metatrader-expert-advisors/Account-Protector/
