### ISSUE TITLE
Как изменить Risk/Reward в советнике Position Sizer (ver 3.07)

### ISSUE THREAD

**Issue by Dariolable** [EarnForex/PositionSizer#103]
Как изменить Risk/Reward в советнике Position Sizer (ver 3.07)?
_Для примера:_
При установке значений риска 0,13% (и при неком стоплоссе) - имеем RR=7,77 в столбце INPUT.
НО по факту при торговле получаем в итоге RR=4,26 в столбце RESULT.
Как так происходит - куда девается почти 45% RR? 
Чем руководствуется программа выставляя определённый размер лота из-за чего падает RR? Ведь мы же отталкиваемся от % риска?
**Какие настройки сделать**, чтобы значение INPUT равнялось по факту торговли значению RESULT? Получается, что при торговле мы недобираем прибыль, если программа уменьшает лотаж.

![222](https://github.com/user-attachments/assets/dadd98d2-1cf6-45a0-944e-1a3afe4ff330)

**Comment by EarnForex** [comment]
Потенциальная прибыль ниже, потому что у вы платите комиссионные за торговлю.
Значиения из Result не могут равняться значениям из Input, если вы платите комиссионные.

**Comment by Dariolable** [comment]
Но как так -то? Комиссия стоит 3$ - у нас куплено 4.32 лота = 12,96$ потеря на комиссии. Вычитаем 504.46 - 12,96 = 491,5 $ чистая прибыль даже за вычетом комиссии. А в столбце Result - стоит сумма 276,48. Куда девается остальная сумма?
КАК программа рассчитывает КАКИМ лотом входить, если RR не выходит таким же, как в прогнозируемых вычислениях (столбец INPUT)?

**Comment by EarnForex** [comment]
Вы не из того вычитаете потерю от комиссии. Смотрите, при текущем размере позиции (4.32) на комиссию уходит 25,92$ (12,96$ надо умножать на 2 так как вы указываете одностороннюю комиссию и эта сумма списывается при входе и потом при выходе). То есть, из вашего заданного риска (64,86$) остается всего 38,94$ на убыток по сделке. Потенциальный убыток по стоп-лоссу у вас 9 пунктов, что при размере позиции в 4.32 дает 38,88$. 38,88$ + 25,92$ = 64,80$. Увеличение размера позиции даже на 0.01 лота привело бы к превышению вашего заданного риска.

Программа не принимает во внимание ни RR ни потенциальную прибыль при расчете размера позиции. Размер позиции расчитывается на основании риска.

**Comment by Dariolable** [comment]
У меня брокер списывает комиссию 1 раз = в примере 12,96$ (это же не потери на спреде 2 раза).
И тут самое главное - я не получаю необходимый мне RR.
Только если не ставлю комиссию или ставлю её 0$ в окне программы - то и расчетный и фактический **после торговли** RR - выходят как надо. 
Получается мне проще не ставить в окно программы комиссию и "терять" в статистике 12,96$ на комиссии, чем НЕДОПОЛУЧАТЬ из-за кривого уменьшенного лотажа программой - 45% прибыли. Это же гигантское расхождение! 
Подобная ошибка была и в другой программе другого автора и он исправил её после моего письма. И лотаж стал рассчитываться таким образом, чтобы RR по сумме всегда выходил нужным трейдеру и при этом риск на сделку включал в себя и комиссию (1 раз!).
Не буду настаивать на своей позиции - ваша программа, ваши правила, ваши формулы. Просто тогда не буду использовать окно с комиссией.
Благодарю, что упрощаете нам работу с рынком.

**Comment by EarnForex** [comment]
> У меня брокер списывает комиссию 1 раз = в примере 12,96$ (это же не потери на спреде 2 раза).
Если у вас брокер списывает комиссию в 3$ с лота один раз, то в поле комиссии нужно указывать 1.50.

> Только если не ставлю комиссию или ставлю её 0$ в окне программы - то и расчетный и фактический после торговли RR - выходят как надо.
Такое может получаться только, если ваш брокер вообще не списывает комиссию за сделку. Если бы в приведенном выше примере вы поставили комиссию равной 0, то размер позиции получился бы 7.20. В случае проигрыша вы бы потеряли 64,80$ + 21,60$ = 86,40$, а в случае выигрыша получили бы 630,00$ - 21,60$ = 608,40$, то есть R/R = 7.04, а не 7.77. При этом потенциальный убыток превышал бы заданный риск.

> Получается мне проще не ставить в окно программы комиссию и "терять" в статистике 12,96$ на комиссии, чем НЕДОПОЛУЧАТЬ из-за кривого уменьшенного лотажа программой - 45% прибыли. Это же гигантское расхождение!

Вы путаете причину и следствие. R/R он какой есть, такой есть, а торговать с ним или нет - это уже вам решать. Чтобы "не терять" в данном случае 45% прибыли, вам надо увеличить риск. Иначе зачем вы пользуетесь инструментом, который рассчитывает позицию таким образом, чтобы ограничить риск до заданного?
