### ISSUE TITLE
Improvement: Offset for Breakeven

### ISSUE THREAD

**Issue by Vanbrugg** [EarnForex/PositionSizer#104]
Hi!

I suggest to add a new variable: Breakeven Offset

This offset could work as a "buffer". A trader could have in mind commission, spread and slippage. To compensate this I set the SL manually a couple of points _after_ the entry.

Currently the Breakeven places the SL on the exact same position of the entry price. With the offset the placement would be entry + XX points on buy orders or entry - XX on sell orders.

Example: 
Entry: 1.5010
Offset: 10

On BUY position - Breakeven would be placed at: 1.5020
On SELL position - Breakeven would be placed at: 1.5000

**Comment by EarnForex** [comment]
If you set the **UseCommissionToSetTPDistance** input parameter to _true_, it will start taking into account the commission when setting BE. If you would like a more advanced BE mechanism, you'd have to use a separate EA for that.

**Comment by Vanbrugg** [comment]
> If you set the **UseCommissionToSetTPDistance** input parameter to _true_, it will start taking into account the commission when setting BE.

Yeah! That's exactly what I looking for! Thanks! :)

**Comment by Vanbrugg** [comment]
> If you set the UseCommissionToSetTPDistance input parameter to true, it will start taking into account the commission when setting BE.

Yeah! That's exactly what I looking for! Thanks! :)
