### ISSUE TITLE
Improvement: Hotkeys per Asset

### ISSUE THREAD

**Issue by Vanbrugg** [EarnForex/PositionSizer#105]
Hi!

Currently I can define a global hotkey to execute an order. But this refers only to the active chart.

**So I have some suggestions:**
1st: Whould it be possible to extend the hotkey feature so that I can link a hotkey to a specific asset?
2nd: In addition to the 1st point, we need a hotkey to close these trades.
3rd: We need a key "manual breakeven".

**Theoretical solution:**
Link the hotkeys to a specific asset (i.e. EURUSD).

**Example:**
Hotkey 1 for open an order: [ASSET] ; [HOTKEY1]
Hotkey 2 for close all open orders: [ASSET] ; [HOTKEY2]
Hotkey 3 for placing breakeven manually: [ASSET] ; [HOTKEY3]

For simplification: The code for this type of hotkeys could be implemented as "single code fragment" - that means: no loop or automation. Why? Every trader could change the needed amount of hotkeys (code fragments) for themselves in the code. ;)

**Comment by EarnForex** [comment]
Hello!

For opening a trade in another symbol, do you mean that you already have a chart for that symbol open in the platform (but the chart isn't active) and the PS is running on it? Or do you mean that the PS just applies the same inputs from the current chart to a different symbol and tries to open such a trade?

**Comment by EarnForex** [comment]
For options 2/3, there is an existing solutions: [close-all](https://www.earnforex.com/metatrader-scripts/close-all-orders/) and [breakeven](https://www.earnforex.com/metatrader-scripts/breakeven/) scripts that can be pre-configured according to a trader's needs and assigned hotkey via MetaTrader's builtin hotkey mechanism, which is even better than what can be accomplished via MQL code.

**Comment by Vanbrugg** [comment]
> For opening a trade in another symbol, do you mean that you already have a chart for that symbol open in the platform (but the chart isn't active) and the PS is running on it? Or do you mean that the PS just applies the same inputs from the current chart to a different symbol and tries to open such a trade?

Let's say you have two charts opened: 1x EURUSD, 1x GBPUSD. If you know want to place an order via hotkey the order is placed for the chart (asset) that is active. If I have activated (clicked) on the chart with EURUSD, the order is placed for EURUSD. If I want to place an order in GBPUSD, I have to click (activate) the other chart (GBPUSD).

Currently it's not possible to place an order to a specific asset (unless you activate the chart).

Let's say I have six charts opened (six different assets). If I want to place orders I have to click on each chart and THEN could press the hotkey. That's complicated and makes the use of the hotkey less useful, in my opinion.
If I work with these six charts (assets) it would be necessary to have six hotkeys to place trades no matter what chart is active.

**Comment by Vanbrugg** [comment]
> For options 2/3, there is an existing solutions: [close-all](https://www.earnforex.com/metatrader-scripts/close-all-orders/) and [breakeven](https://www.earnforex.com/metatrader-scripts/breakeven/) scripts that can be pre-configured according to a trader's needs and assigned hotkey via MetaTrader's builtin hotkey mechanism, which is even better than what can be accomplished via MQL code.

Okay, thanks for the advise! Ich will check this out.
