### ISSUE TITLE
Invalid TP issue on some pairs like EURGBP

### ISSUE THREAD

**Issue by ecomaven** [EarnForex/PositionSizer#39]
![image](https://user-images.githubusercontent.com/14871679/157180977-052b6b34-f3f1-4a76-a289-d086160865b8.png)

Noticed an issue as PSC will not calculate risk, reward or lots on a few pairs but works on others. 
Strangely it does not display the Entry, TP or SL lines automatically on those pairs despite the Order Type being set to "Instant". 
When changed to pending and  Entry/TP/SL prices manually entered, still gives "Invalid TP"

![image](https://user-images.githubusercontent.com/14871679/157182781-d09bec04-a019-44fb-98fe-e08e64ac483f.png)

**Comment by EarnForex** [comment]
Which broker/account is that? Is there any output in the Experts tab of the Terminal subwindow?

**Comment by ecomaven** [comment]
Broker is IC Markets
![image](https://user-images.githubusercontent.com/14871679/157197184-ca493808-9058-4dc3-87f3-b225e01eb50f.png)

**Comment by EarnForex** [comment]
And which account type at IC Markets?

**Comment by ecomaven** [comment]
raw spread

**Comment by ecomaven** [comment]
demo

**Comment by EarnForex** [comment]
Can you provide the list of steps that you made to get this issue? I've just tried the PSC on EURGBP IC Markets Raw Spreads account and I couldn't reproduce the issue.

**Comment by ecomaven** [comment]
Strange. I just tried it again now and it works without my doing anything.

The steps are the simple and same. PSC is loaded as part of my template. 
- I open PSC and click "show lines". 
- Then click "Order type". 
- Then drag lines as necessary.

**Comment by EarnForex** [comment]
Maybe some weird setting value got saved into your template? If you add a fresh PSC does it have the same issue?

**Comment by ecomaven** [comment]
Was not a weird setting in template cause when i changed the pair from EURGBP to another pair EURJPY it worked but once I took it back to EURGBP it resumed showing that "Invalid TP".

As of now both with my template and fresh PSC, it works.

**Comment by EarnForex** [comment]
> As of now both with my template and fresh PSC, it works.

By "it works" you mean that the issue is showing up or that everything gets calculated correctly?

**Comment by ecomaven** [comment]
Everything is getting calculated correctly atm

**Comment by EarnForex** [comment]
Did the issue appear just after upgrading the PSC from the previous version to 2.42?

**Comment by ecomaven** [comment]
Actually happened in 2.41 which spooked me and actually made me upgrade to 2.42. When the same thing happened in 2.42, I decided to write this issue

**Comment by EarnForex** [comment]
Wow! That's very strange. Let's wait for it to appear again then. Please try to remember all the preceding steps if this appears again, so that I could try to reproduce it and find the underlying cause. Thank you!
