### ISSUE TITLE
Help with SL Panel Button

### ISSUE THREAD

**Issue by cpoolrn** [EarnForex/PositionSizer#47]
Hello,

I recently purchased a new computer and reinstalled Position Size Calculator v2.42. After entering all the inputs, I can't get the "Stop-loss:" button to work in the main panel. This use to move the SL line to a specified number of pips below/above the entry line. The Take-profit button works appropriately and moves the TP line below/above the entry line when activated, but the SL button doesn't do anything. Any suggestions? I've tried re-compiling it, and still doesn't work.

Chris

![1657998753668](https://user-images.githubusercontent.com/46605837/179370326-b2f3093e-3262-43fc-8a86-46fd7cd37587.png)
![1657998777487](https://user-images.githubusercontent.com/46605837/179370329-fcbb9807-2428-4777-add5-434be1065072.png)
![1657998897329](https://user-images.githubusercontent.com/46605837/179370339-afd6f2ef-73c7-4297-8c57-f7ef80ec5819.png)

**Comment by EarnForex** [comment]
You need to set some default SL value for the button to appear.

**Comment by EarnForex** [comment]
Looks to be a non-issue.
