### ISSUE TITLE
Commodities and stock not position sized with risk.

### ISSUE THREAD

**Issue by linderseen** [EarnForex/PositionSizer#48]
[POS bug](https://vimeo.com/734628387/e4dba2b6cb)

Sorry for no voice. Forgot i could say something hehe. 
Okay what the problem is that with commodeties and stock the POS dosnt correct the position size.  As you can se with the 3 examples. I show also in last example with FX pairs it works just fine. But every commodity and stock it wont calculate the position size to the risk.

**Comment by EarnForex** [comment]
Hello!

Thank you for reporting! Unfortunately, despite watching the video, I still don't understand the problem at hand here. Could you please provide one example (preferably with screenshots) where the calculated value is wrong and what the correct size should be instead?

**Comment by linderseen** [comment]
https://vimeo.com/734672349/b7abd29b2e

 

I added voice so it should be more easy to understand 😊

 

Från: EarnForex ***@***.***> 
Skickat: Friday, 29 July 2022 11:21
Till: EarnForex/PositionSizer ***@***.***>
Kopia: linderseen ***@***.***>; Author ***@***.***>
Ämne: Re: [EarnForex/PositionSizer] Commodities and stock not position sized with risk. (Issue #48)

 

Hello!

Thank you for reporting! Unfortunately, despite watching the video, I still don't understand the problem at hand here. Could you please provide one example (preferably with screenshots) where the calculated value is wrong and what the correct size should be instead?

**Comment by EarnForex** [comment]
I see... The likely reason is that the actual profit calculation mode for that symbol doesn't match the one returned by the trading server to the MQL5 programs (Position Sizer in this case). Of course, it can also be some kind of a bug in the PS EA.

Do you know how can I get their demo MT5? I registered with TFF, but I don't see a demo account option anywhere. With a demo platform, I'd be able to debug this.

**Comment by linderseen** [comment]
Use this logins:

 

Login: 957886

Password: Oyl6fYDLF456iW

Server: TrueProprietaryFunds-Demo

 

Download there MT5 as it’s a MT5 account. 

 

Was thinking also could be symbols but then the FX shouldn’t work.  Happy hunting and keep me updated. Will also try it on other funded accounts to se if the same problem is there. 

Tomas

 

Från: EarnForex ***@***.***> 
Skickat: Friday, 29 July 2022 13:28
Till: EarnForex/PositionSizer ***@***.***>
Kopia: linderseen ***@***.***>; Author ***@***.***>
Ämne: Re: [EarnForex/PositionSizer] Commodities and stock not position sized with risk. (Issue #48)

 

I see... The likely reason is that the actual profit calculation mode for that symbol doesn't match the one returned by the trading server to the MQL5 programs (Position Sizer in this case). Of course, it can also be some kind of a bug in the PS EA.

Do you know how can I get their demo MT5? I registered with TFF, but I don't see a demo account option anywhere. With a demo platform, I'd be able to debug this.

**Comment by EarnForex** [comment]
Thank you! I'll check it now.

**Comment by EarnForex** [comment]
Found the bug! It appears when you switch from a different kind of symbol (Forex) to another one (e.g., CFD Leverage). If you open a new chart for NGAS and apply the Position Sizer there, it will calculate correctly. I will fix this in the next version.

**Comment by linderseen** [comment]
Aaaa wow nice job. Great work and great you solved the problem. Look forwards to the update and if I find anything else I will inform you 😊 😊

 

Från: EarnForex ***@***.***> 
Skickat: Friday, 29 July 2022 13:56
Till: EarnForex/PositionSizer ***@***.***>
Kopia: linderseen ***@***.***>; Author ***@***.***>
Ämne: Re: [EarnForex/PositionSizer] Commodities and stock not position sized with risk. (Issue #48)

 

Found the bug! It appears when you switch from a different kind of symbol (Forex) to another one (e.g., CFD Leverage). If you open a new chart for NGAS and apply the Position Sizer there, it will calculate correctly. I will fix this in the next version.

**Comment by EarnForex** [comment]
Fixed in 3.02.
