### ISSUE TITLE
New feature request: Break even by percentage

### ISSUE THREAD

**Issue by LeVannucci** [EarnForex/PositionSizer#49]
It'd be nice to have the option to insert a break even by percentage.
We could type de percentage, for instance, 50%, and when the price hits 50% fo the TP the SL is moved to break even.
Thanks.

**Comment by EarnForex** [comment]
Sorry, I don't think it's a good idea for the Position Sizer. I even discarded such an idea for the [Account Protector](https://github.com/EarnForex/Account-Protector), which would be much more suited for its implementation.
