### ISSUE TITLE
Add option to refresh Stop loss automatically

### ISSUE THREAD

**Issue by Kumzy** [EarnForex/PositionSizer#50]
Hello,

It would be great if we can add an option to automatically refresh the stop loss value (following the stop loss in points entered in the settings)

the issue is that I have to click on the stop loss to refresh the value because entering a trade.
I would prefer the stop loss to refresh automatically.

When setting stop loss in the settings to 100 points for example. I would like it to move like the entry.

Example with SL = 100 points (Long position)
- Entry price is: 1.9048
- SL: 1.9038

Price is moving down to 1.9045 on the next tick
- Entry price is now: 1.9045
- I would like SL to be automatically: 1.9035

**Suggestion**:
Add an option to refresh automatically the stop loss on each tick

**Comment by EarnForex** [comment]
Did you try setting the **SLDistanceInPoints** input parameter to _true_?

**Comment by Kumzy** [comment]
That's the input that I filled for the SL
<img width="449" alt="image" src="https://user-images.githubusercontent.com/5995441/184316370-8c1d060e-3dd7-4c2a-ac86-a2df78dd5c25.png">

**Comment by Kumzy** [comment]
Working with SLDistanceInPoints, Stop-loss price is replaced with the distance in point. Working fine there. Thank you
