### ISSUE TITLE
Moving SL/TP from default ATR requires several attempts during high volume

### ISSUE THREAD

**Issue by MuttleyBerks** [EarnForex/PositionSizer#52]
I've had this issue with 2.x and 3.x. Same issue in 3.0.2.

I've compiled with the following changes:

input bool ShowATROptions = true
input double DefaultATRMultiplierSL = 1
input double DefaultATRMultiplierTP = 2
input ENTRY_TYPE DefaultEntryType = Pending

1. Open Position Sizer on chart (SL and TP lines show correctly)
2. Attempt to drag the SL/TP can required 10+ attempts as it keeps resetting back to the original last position

It seems that on a new tick it will get reset unless you moved it before the tick came in. So it's easier to set when market volume is low.

BTW, this is an amazing tool and I'm always recommending it. Unless you've coded in MQL you'll have no idea the amount of time and effort this project must have taken. Much respect team! ;-)

**Comment by EarnForex** [comment]
Hello!

The lines aren't supposed to be dragged manually when in some non-zero ATR multiplier values are given. Set multipliers to zero and you should be able to move the lines.

**Comment by MuttleyBerks** [comment]
I've just tried setting the ATR multipliers to 0. It's definitely better but occasionally still snaps back when moving the lines. 

Having default ATR stops are useful as a starting point then I may adjust the entry and SL.

**Comment by EarnForex** [comment]
Are you on MT4 or on MT5?

**Comment by MuttleyBerks** [comment]
MT5.

**Comment by EarnForex** [comment]
I will look into it! Thanks for reporting!

**Comment by EarnForex** [comment]
Should be addressed in 3.03.
