### ISSUE TITLE
Consider setting Pound Averaging feature for Position Sizer in both MT4 & MT5 versions?

### ISSUE THREAD

**Issue by lueny-toons** [EarnForex/PositionSizer#53]
Hi. Great work as always... I hv been a huge fan and user of Position Size Calculator since few years ago with the one using PSC Script to quickly put in a trade. This new Position Sizer is amazing. Kudos to the Team in its further development.

I have a suggestion... One which I believe if can be implemented will be a game changer for Position Sizer EA. I have been trading lately using the Pound Averaging Strategy used by big boys taught by my mentor. What this does is to open multiple PO POS (position) at various prices but all with the same SL. So, e.g. if I decided to execute a netting strategy with 5 Sell Limit POS because price is playing out based on my strategy parameters. The very 1st POS I set either an instant or Sell Stop to trigger the 1st order for me to be in play. As I believe there would be a retrace before moving forward to my intended analysis, I will then set Sell Limit orders. So, the next 5 Sell Limit POs I would like to input POS 1 at 1.0000, POS 2 at 1.0010, POS 3 at 1.0020, POS 4 at 1.0030 and POS 5 at 1.0040 with all these 5 Pending Orders are with the same SL value. However, with the TP I would like to have options to have all TP value of each POS the same price value (OR)..., manually/by pulling the line on the chart to set each POS differently. Meaning e.g. POS 1 the TP set at 0.9980, POS 2 the TP set at 0.9980, POS 3 the TP set at 0.9960, POS 4 the TP set at 0.9940 and POS 5 the TP set at 0.9940

Pound averaging strategy ensures that I have a better price when price goes against initially but still keeping the same SL value of each POS. So, on the last POS essentially I'm risking a smaller SL amt but when price goes in favour, my 5th, 4th and 3rd POS will start amassing more pips and better returns than the 2nd and 1st POS. If for whatever reasons price stalls and doesn't go beyond my 1st POS I can close all the POS' with still a sizeable +ve TP amount. This is in itself controlling my risk management with a smarter approach. But if price does go in my favour puncturing through POS 1 then I'm in good profit for all 6 POS' and just wait till price hits the already set individual TP values for each of the 5 POS'.

So..., that's what I see can be a wonderful feature if the Pound Averaging feature can be coded into Position Sizer EA. I'm not sure if it could be done (as I'm a noob in coding, and thus I leave it to you to see if it can be done?) but if it can..., this definitely is a game changer in my eyes as I've learnt this from my mentor and it's a wonderful strategy that has shown superb results. We're all trading using this strategy to maximise profits when it works out and if it doesn't by going against, we're still able to manage our funds at the end, coming out with +ve returns.

I hope you see the value in such a feature and if this could be done and added into Position Sizer EA in the next update I am sure it will be a biggie for everyone to enjoy :)  Anyway, you're the expert and let me know how this goes... Can it be done and is it useful... Cheers

**Comment by EarnForex** [comment]
I'm not sure it's good idea to try to implement something like this into the Position Sizer.
