### ISSUE TITLE
Possible bug with using zero stop loss in short trade

### ISSUE THREAD

**Issue by IkoLogs** [EarnForex/PositionSizer#54]
Hi
Thanks very much for this wonderful EA. Your effort is very much appreciated.

When setting up a short trade on the EA, setting zero stop loss in the edit box automatically by itself changes the Short button to long.
The button goes from showing Short to showing Long.

For now i just use very high stop loss to avoid the problem.

Cheers.

**Comment by EarnForex** [comment]
Hello!

Position Sizer isn't intended to be used with zero stop-loss. Why would you want to set a zero stop-loss in a tool that is supposed to calculate the position size based on your stop-loss?

**Comment by IkoLogs** [comment]
Oops forgot about the risk factor.
I am back  testing hedging strategy  that works with no stop loss.
in effect a trade in opposite direction replaces the stop loss.
I am not quite sure how PSC could handle that myself, but i am hopeful of wonders in future updates.

On Another Note.{Existing feature gone missing in 3.02}
Also noticed a feature that went missing in 3.02 , its the fact that putting zero in take profit box used to mean no trade for that tp. But now with zero in all tp boxes you get trade for each tp. I have to go in EA settings menu to change number of tp, but its faster to do it by just setting tp to Zero.

Cheers

**Comment by EarnForex** [comment]
You can still adjust the volume share on the Trading tab. Zeroing the TP value doesn't remove the trade completely to allow for zero-TP trades in the multiple-TP mode.

**Comment by IkoLogs** [comment]
i see thanks for the tip,  did not think of testing with zero share to disable tp trade.
cheers

**Comment by EarnForex** [comment]
Should be addressed in 3.03.
