### ISSUE TITLE
Lot size with multiple profit targets

### ISSUE THREAD

**Issue by jmmac1973** [EarnForex/PositionSizer#55]
Hi,
Thanks for the great tool.

I use it with multiple profit targets in an account with little funds. The issue I observe is that the distribution of the lot size by the different portions of the trade doesn't look correct. 
I attach an example where I have 4 PT with 25% each, and one of the portions has 0.04 and the others 0.01. Ideally, they should all have the same lot size but since that's not possible (unit is 0.01 lots), I believe a 0.02, 0.02, 0.02, 0.01 lots would make more sense.

There are other small issues relative to multiple PT:
- When the number of PT is changed, the percentage distributions of the PT get messed up but don't become red to indicate an error.
- If I have 3 PT, it accepts 33% in each (doesn't become red) but that gives different lot sizes than 34%, 33%, 33%. seems something is not quite right.

![Screenshot 2022-11-10 145609](https://user-images.githubusercontent.com/26794717/201131760-9be1048c-f820-4911-9d96-0c0846b225cf.png)

Kind Regards, Jaime.

**Comment by EarnForex** [comment]
Hello!

Thank you for reporting!
I will consider changing the volume distribution algorithm. I will also fixed the bug for when the TakeProfitsNumber is changed.

As for the third bug you mention, I don't quite understand the issue. Could you please provide more details?

**Comment by jmmac1973** [comment]
Hi,

Firstly, how do one divide evenly between 3 positions (33.33..% x3) ? The expert doesn't allow decimals so, if I enter 33 in all positions, does that mean each has 33.33% ?

In that situation (3 x 33%), the lot distribution seems worse than in previous example I showed. See attached image.

Kind regards,
Jaime Machado

![Screenshot 2022-11-13 122316](https://user-images.githubusercontent.com/26794717/201521514-a51aec8a-d950-4709-8a1c-db52452f05d9.png)

**Comment by EarnForex** [comment]
3 x 33% is correct, but for some reason it doesn't work well in this case. Your calculated position size was 0.03 lot?

**Comment by jmmac1973** [comment]
> 3 x 33% is correct, but for some reason it doesn't work well in this case. Your calculated position size was 0.03 lot?

Yes, 0.03 lot total.

**Comment by EarnForex** [comment]
Should be addressed in 3.03.
