### ISSUE TITLE
SL is too far away from the current price

### ISSUE THREAD

**Issue by atifhussain18** [EarnForex/PositionSizer#56]
This happens randomly. The SL sometimes is placed so far away from the current price that we just can't move the SL line even after zooming out as it's very hard to find. Instead we have to enter the SL price manually. This wasn't an issue in v3.01 where we could just click on the Stop Loss button (if the SL was placed far away) and SL would be placed near to the current price. But that ability to click on the Stop loss button is no longer present too.

![image](https://user-images.githubusercontent.com/47064709/205427827-f22b3e23-1054-499f-8af7-c0cef9bd8678.png)

**Comment by EarnForex** [comment]
Please set the Default SL input parameter to some non-zero value.
