### ISSUE TITLE
Can't move stop-loss line with mouse

### ISSUE THREAD

**Issue by hoangnv-bkhn** [EarnForex/PositionSizer#60]
Thanks for the great tool

I noticed this bug when I was using it, can you guys check it again?

After adding the Position Sizer to a chart and fully setting it up, I saved the template.
When opening a new chart and loading the saved template and selecting "Show lines", only the take-profit lines can be moved with the mouse. The stop-loss lines cannot be moved and must be edited by filling in the input box.

As shown in the image below only the take-profit lines (green) have squares on the left and can be moved.
The stop-loss line (red), has no squares on the left and cannot be moved with the mouse.
![image](https://user-images.githubusercontent.com/58356409/227454155-c11f44bf-c61d-4858-87c5-0e4ec348031f.png)

Position Sizer version: 3.02 (2022-08-12)
OS: Windows 10 Pro 21H2

Best Regards, 
Stephen

**Comment by EarnForex** [comment]
Hello!

Just double-click the stop-loss line and it will become selected for movement.
