### ISSUE TITLE
Breakeven to account for commission

### ISSUE THREAD

**Issue by twoplusone** [EarnForex/PositionSizer#63]
Hello, it would make sense to have the Trading/Breakeven function to have into consideration commission per lot.

On DoBreakEven() function, the code could check if there's a commission set and calculate how many points it needs to cover for the comission cost.

Something pseudo like

CommissionPoints = CalculateCommissionPoints()
BE = POSITION_PRICE_OPEN + CommissionPoints + sets.BreakEvenPoints

if SYMBOL_BID >= BE && POSITION_PRICE_OPEN > POSITION_SL
    PositionModify (ticket, POSITION_PRICE_OPEN + CommissionPoints, POSITION_TP)

Thank you for the consideration!

**Comment by EarnForex** [comment]
Thanks! I will implement this in the next version.

**Comment by EarnForex** [comment]
Should be fixed in 3.04. Thank you!
