### ISSUE TITLE
Increase / decrease take profit buttons causes freeze

### ISSUE THREAD

**Issue by twoplusone** [EarnForex/PositionSizer#64]
Hello,

after adding the EA to a chart, click on Take-profit button then try to increase or decrease with the + / - buttons causes the EA to freeze.
A workaround solution is to first add a second take profit which can be removed and then the + / - buttons work as expected.

I presume it may be related to sets.TP array but cannot debug since not yet familiar with MQL5.

Attached is a video capture of the issue: [ps.webm](https://user-images.githubusercontent.com/17060482/232283199-bef17e98-1fad-4e44-8477-1731bbd31d31.webm)

Thank you for this great EA btw!

**Comment by EarnForex** [comment]
Thank you for reporting! This will be fixed in the next version.

**Comment by EarnForex** [comment]
Should be fixed in 3.04.
