### ISSUE TITLE
panel keeps disappearing (mt5)

### ISSUE THREAD

**Issue by paymanz** [EarnForex/PositionSizer#65]
hi , on the version 3.03 for MT5 the panel keeps disappearing . EA still attached to chart but the panel is not visible unless open F7 and change some setting , then the panel becomes visible again.  mt5 built 3661

**Comment by EarnForex** [comment]
What steps do you take before it disappears?

**Comment by paymanz** [comment]
> What steps do you take before it disappears?

nothing specific , I'm not sure. I'm on the chart and then notice its not here, maybe every 30m-1h it happens. then i do toggle the "start panel minimized" and panel visible again.

**Comment by EarnForex** [comment]
That's weird. I've never encountered such an issue here. It would be really helpful if you write more info here if you encounter it again, like what settings you were using or maybe if you were using some other indicators on the same chart.

**Comment by paymanz** [comment]
my EA setting https://www.sendspace.com/file/vrywf8
indicators i have on my chart :
https://www.mql5.com/en/market/product/19226?source=Unknown
https://fxssi.com/forex-news-indicator-mt4
https://www.sendspace.com/file/w35qoz
my template: https://www.sendspace.com/file/6whgq1

**Comment by EarnForex** [comment]
I was only able to check the Show_Pips indicator (it's fine) because it's the only open-source one, but it is entirely possible that one of the other indicators simply deletes all objects from the chart under certain conditions. This would explain the PS panel disappearing.

**Comment by paymanz** [comment]
so it must be one of these tools causing the problem in your opinion. ok thanks i try to remove them and see.

**Comment by paymanz** [comment]
its apparantly the pip show indicator causing it. when i remove it problem solved. thanks for advise.
