### ISSUE TITLE
Little graphic bug *

### ISSUE THREAD

**Issue by maccieddu** [EarnForex/PositionSizer#66]
Good Morning,
thanks for the fantastic work done with the last update, I'm very happy that you have implemented the things I reported previously.

I found a little graphical bug when the panel is minimized the * of account balance is still on chart

![bug1](https://user-images.githubusercontent.com/24259316/233087708-6ee403f4-7362-4b4c-ac73-ada9624d6be0.png)
![bug2](https://user-images.githubusercontent.com/24259316/233087711-0de5eee0-5907-4039-aacf-de14f0dfa8c1.png)

**Comment by EarnForex** [comment]
Thank you for reporting!

**Comment by maccieddu** [comment]
I have found another little graphic bug, if i change order type with hotkey and the panel is minimized the + and - button remain on the graph.
![Immagine 2023-04-26 155753](https://user-images.githubusercontent.com/24259316/234599086-72b019b1-2150-4026-82c8-c5fb34b00e5d.png)

**Comment by EarnForex** [comment]
Thanks! Will work on it for the next version.
