### ISSUE TITLE
risk tab: it shows positive value when sl is in negative

### ISSUE THREAD

**Issue by paymanz** [EarnForex/PositionSizer#71]
Hi , on risk tab the risk value is positive when sl is in negative(for example when buy position and sl is below entry) and when sl is in positive (when its at BE point or sl is trailing above entry) . 

Would be nice if it get fixed.

Thank you very much 🙏

**Comment by EarnForex** [comment]
Hello!

How did you get SL to be negative?

**Comment by paymanz** [comment]
> Hello!
> 
> How did you get SL to be negative?

I mean when you open a trade your sl is in negative obviously, meaning if price hit it you'll loose money. But when you look at the risk tab the risk section value shows a positive number, and when you move your sl into profit it shows a negative number , i think it should be vice versa. 

I hope i have explained clear.

**Comment by EarnForex** [comment]
I still don't understand how you managed to move the SL into profit. Could you please show a screenshot of what is going on?

**Comment by EarnForex** [comment]
Sorry, it's only now that I've noticed that you are asking about the Risk tab, so perhaps, you are asking about the actual stop-loss of an already open position and not about the SL line of the position being calculated by the Position Sizer? In that case, that's what it actually does - it shows the current portfolio risk in negative (with the minus sign) when the trade's SL is in the profit, so there is no actual risk for it.

For example in MT5, see this screenshot:
![image](https://github.com/EarnForex/PositionSizer/assets/48102957/66f4f337-fae7-41db-a413-a0f153e3272f)
