### ISSUE TITLE
Hotkey to move the stoploss at breakeaven

### ISSUE THREAD

**Issue by maccieddu** [EarnForex/PositionSizer#72]
Hello, first I wanted to continue thank you for your immense work with Position Sizer, I have been using it for quite long time now and its amazing. I would like to ask you if it was possible to implement an hotkey like "B" for example, to move the stop loss of an active running trade at breakeven calculated with the commission for round trip in mind or with the option that you have included some time before. Thank you again for the efforts you do to mantain this fantastic piece of software!
![Cattura](https://github.com/EarnForex/PositionSizer/assets/24259316/d99c2a85-e2ce-4ae7-a591-cb3efb322004)

**Comment by EarnForex** [comment]
Best solved with a separate script.
