### ISSUE TITLE
Something wrong when calculator lot size with commision

### ISSUE THREAD

**Issue by henzycuong1** [EarnForex/PositionSizer#73]
Today, I entered a short position on XAUUSD. I have set up like image
![image](https://github.com/EarnForex/PositionSizer/assets/55269394/172d430d-4c32-476c-8bfa-f031f7ec95ef)
and that position hit stop-loss. 
![image](https://github.com/EarnForex/PositionSizer/assets/55269394/54d9903f-27b4-45e9-8a7a-7caca863de60)
But I realize, the sum of profit and commision is 6.74, which means 3.26$ be missed to calculator lot size

**Comment by EarnForex** [comment]
That's because you entered the round-turn commission ($16.00 per lot) instead of the one-way ($8.00 per lot).

**Comment by henzycuong1** [comment]
> That's because you entered the round-turn commission ($16.00 per lot) instead of the one-way ($8.00 per lot).

what is that mean ? sorry, I don't understand that. My broker got $16.00 per lot XAUUSD, and I set "Commision (one-way) per lot" is $16 but you said it's "round-turn". How can I switch it ?

**Comment by henzycuong1** [comment]
> Your broker has $16.00 round-turn commission, which means that they take $8.00 when you open the trade and then $8.00 when you close it. The Position Sizer's commission field expects the size of your one-way commission as an input (which is $8.00 in your case). So, you just enter 8.00 there.

thank you so much
