### ISSUE TITLE
Error in margin calculation for XAUUSD 

### ISSUE THREAD

**Issue by maccieddu** [EarnForex/PositionSizer#74]
Hi, i have noticed that in the margin tab the calculation for the specific contract is incorrect...
On the specific contract the margin is calculated like this:
(trade size * contract size * price / leverage) * margine rate
On this particulare broker the leverage is 4 and the margin rate is 3 so the calculation is:
(0.07 * 100 * 1900.00 / 4) * 3 = 9975$
But the position sizer give me the value of
(0.07 * 100 * 1900.00 / 4)  * 2.5 = 8312.5$ that is the value calculated with margin rate maintenace 2.5

Is it possible to add a textbox were insert a custom margin rate alongside the custom leverege that is in place now or let the user chose the margin rate initial or maintenace? 

![margin](https://github.com/EarnForex/PositionSizer/assets/24259316/fd45b9cc-498c-4baf-87ad-114505c74285)
![image](https://github.com/EarnForex/PositionSizer/assets/24259316/405e4aca-62dd-408b-a53a-06dd8b3adf1f)

**Comment by EarnForex** [comment]
Thank you for letting me know. I will consider adding both calculations.

**Comment by EarnForex** [comment]
Hello! Could you please let me know which broker is that, so I could test?

**Comment by maccieddu** [comment]
Hello, it's a prop firm not a broker...

**Comment by maccieddu** [comment]
Yes sure, the prop is the5ers.

**Comment by maccieddu** [comment]
Hope you got the demo for testing this fix...

**Comment by EarnForex** [comment]
Sorry, they refused to provide a demo account. I couldn't find any other broker that have different but non-zero initial and maintenance margin. Besides, I've been busy with another project.

I will soon prepare a fix for this and will send you a beta, so you could see if it works in your account.

**Comment by maccieddu** [comment]
Ok, i'm very sad that they not provide you a demo to improve a strument like this... i'm looking for the beta to test your proposed fix and i will tell you if its work. I know its very hard to fix thing without testing in first person

**Comment by EarnForex** [comment]
Hello @maccieddu ! Was this on a netting account or on a hedging one?

**Comment by maccieddu** [comment]
In theory the formula would be this:
(Volume in lots * Contract size * Open market price / Leverage) * Margin Rate? for example:
(0.42 * 100 * 1923.00$ / 10) * 3 = 24229.8 <---- (3 is the initial margin) the account is of 25k

with position size calculator that propose me 0.49 lot max the calculation is this:
(0.49 * 100 * 1923.00$ / 10) * 3 = 28268.1 <---- (3 is the initial margin)

i think the problem is the margin rate used in the formula

**Comment by maccieddu** [comment]
Maybe this lines of code are where the margin is calculated and they use maintenace_margin_rate instead of initial_margin_rate
![image](https://github.com/EarnForex/PositionSizer/assets/24259316/fcb66f96-4780-4a24-b8e5-43b0434d4b7d)

**Comment by EarnForex** [comment]
Yes, please try this one.
[Position Sizer.zip](https://github.com/EarnForex/PositionSizer/files/12936922/Position.Sizer.zip)

**Comment by EarnForex** [comment]
Attached a wrong file in my previous (deleted message). Please use the one attached here.
[Position Sizer.zip](https://github.com/EarnForex/PositionSizer/files/12937291/Position.Sizer.zip)

**Comment by maccieddu** [comment]
It seems to be going much better now.
![image](https://github.com/EarnForex/PositionSizer/assets/24259316/cdbaeda0-1712-4c47-bc71-af2a9acea49d)

**Comment by maccieddu** [comment]
However, I continue to notice very small differences, in the other pairs, between the values calculated with the tool provided by the prop and with the values calculated by the position sizer, at this point I believe that each instrument (forex, indices, metals) has its own formula for the calculation of the required margin.

**Comment by EarnForex** [comment]
Make sure you are attaching the version that I uploaded in this thread. It should say "ver. 3.062" in the header. The last four screenshots show "3.06".

**Comment by EarnForex** [comment]
As for the remaining difference (0.41 vs 0.42), it might be attributed to rounding down vs rounding up. But if you notice a bigger difference, please let me know.

**Comment by maccieddu** [comment]
![image](https://github.com/EarnForex/PositionSizer/assets/24259316/c38e0d66-580e-4b36-affa-b91f228da52a)

**Comment by EarnForex** [comment]
Is the initial margin on SP500 and EURUSD also larger than the maintenance margin?

**Comment by maccieddu** [comment]
![image](https://github.com/EarnForex/PositionSizer/assets/24259316/012f2807-3caa-4221-8aa2-d11e4a7c36eb)
![image](https://github.com/EarnForex/PositionSizer/assets/24259316/89feb8c6-3266-4849-b164-fd50846d96f3)
![image](https://github.com/EarnForex/PositionSizer/assets/24259316/faf5f3f3-de8f-4358-9c25-05d5427af336)

**Comment by EarnForex** [comment]
Thank you! Is your account in USD?

**Comment by maccieddu** [comment]
Yes sir.

**Comment by EarnForex** [comment]
The Position Sizer uses Free Margin for max position size calculation. Perhaps, you have open trades and the firm's calculator is using balance or equity for its calculation? Could you please check?

**Comment by maccieddu** [comment]
I send you screenshot with no trade open, so equity is equal to balance

**Comment by maccieddu** [comment]
Perhaps the problem is that every asset have is own margin calculation? https://www.metatrader5.com/en/terminal/help/trading_advanced/margin_forex
If you read in the last screen shot on the row: calculation, one have type forex and one CFD leverage

**Comment by EarnForex** [comment]
Do you know your account's stop-out level? It's another factor considered by the Position Sizer when calculating the Max Position Size by Margin.

**Comment by maccieddu** [comment]
You are refering to this?
https://www.babypips.com/learn/forex/what-is-a-stop-out-level

**Comment by EarnForex** [comment]
Yes, it's different for each broker. The attached script prints your account's stop-out mode and level when you run it. Could you please let me know what it says?
[PrintStopOut.zip](https://github.com/EarnForex/PositionSizer/files/13024748/PrintStopOut.zip)

**Comment by maccieddu** [comment]
![image](https://github.com/EarnForex/PositionSizer/assets/24259316/13bdd1f3-8cfc-42bd-905a-7bb4ce6e12a1)

**Comment by EarnForex** [comment]
And your current free margin is?

**Comment by maccieddu** [comment]
The account start size is 25000$ now is 24387.90$

**Comment by maccieddu** [comment]
Ah ok now sound good, so the position size is more reliable of firm's indicator if i understand good?

**Comment by EarnForex** [comment]
I don't know. The Max Position Size feature in the Position Sizer is designed so that if you take that trade, you will be as close to the stop-out as possible without actually getting stopped out (OK, you'll probably get stopped out anyway due to the spread, but still...).

It looks like their calculator, doesn't consider the stop-out level at all. So, taking a trade size that it offers will likely result in an immediate stop-out regardless the current spread or anything like that.

**Comment by maccieddu** [comment]
I think you are right, therefore i continue to use position sizer as only reference to risk.
So you think that now implement the double visualization of maintenace and initial margin is worth, maybe the initial margin only is the best option for the broker that provide two different margin rate?

**Comment by EarnForex** [comment]
Fixed in 3.07.
