### ISSUE TITLE
Risk pending order not being calculated

### ISSUE THREAD

**Issue by BarbzYHOOL** [EarnForex/PositionSizer#75]
This EA is great, also thanks to Bernd Skorupinski for showing it.

The risk tab is not working all the time, usually it works fine when I click on "Count pending orders" but at the moment, when i click it, it increases my lot size fine ("Lots") but the Risk Eur or Risk % doesn't change at all

**Comment by BarbzYHOOL** [comment]
I relaunched MT5 and it now says "invalid ex5 file (534)" wtf
i think it happened to me before

It's like it got corrupted while using it????????????????? I'm on Linux with Wine but it still doesn't make sense

**Comment by EarnForex** [comment]
> This EA is great, also thanks to Bernd Skorupinski for showing it.
> 
> The risk tab is not working all the time, usually it works fine when I click on "Count pending orders" but at the moment, when i click it, it increases my lot size fine ("Lots") but the Risk Eur or Risk % doesn't change at all

Could you please show some screenshots of what happens?

**Comment by EarnForex** [comment]
> I relaunched MT5 and it now says "invalid ex5 file (534)" wtf

Did you try recompiling the EA?

**Comment by BarbzYHOOL** [comment]
no, i didn't recompile, i relaunched MT5 and it worked again, but I had to re-attach position sizer to each chart...

What screenshot? it's exactly as I said, in the "risk" tab. You wouldn't see anything on a screenshot, it would require a video to see that the risk doesn't change despite having pending orders (only the lot size changes, not the risk in eur or %)

**Comment by EarnForex** [comment]
> What screenshot? it's exactly as I said, in the "risk" tab. You wouldn't see anything on a screenshot, it would require a video to see that the risk doesn't change despite having pending orders (only the lot size changes, not the risk in eur or %)

I mean the screenshots of before and after with the Trade tab of the platform (where all the positions and orders are listed) visible. It's difficult to fix something without being able to reproduce it, and it's difficult to reproduce an issue without seeing the exact circumstances, under which it appears.

**Comment by BarbzYHOOL** [comment]
ok i'll try next time i see the bug

**Comment by EarnForex** [comment]
Closing for now. Please let me know if this occurs again.
