### ISSUE TITLE
I have to enable "algorithm trading" EVERY DAY

### ISSUE THREAD

**Issue by BarbzYHOOL** [EarnForex/PositionSizer#77]
Every day, charts where positionSizer is enabled and that I traded with yesterday (using algorithm trading) require me to REENABLE this option.

I'm on linux, using MT5 through Wine, is it a bug that only occurs there?

Very annoying

**Comment by EarnForex** [comment]
Hello!

Sorry, I don't use MT5 through Wine, so I cannot say whether that is normal there. However, I know that by default, MT5 disables autotrading on account and profile change. You check the settings via Tools->Options->Expert Advisors.

**Comment by BarbzYHOOL** [comment]
yes it's how i enable it each time, so there is a bug with wine

**Comment by BarbzYHOOL** [comment]
@EarnForex can you help me test this thing? The issue comes when I switch from a profile to another (even though I save the profile after ticking the settings)

How to test: enable algorithmic trading in options, then go to File->Profiles-> Select another
Then press Ctrl+o to open options and see if it's still enabled. For me it is not.
If it is, then go back to the previous profile and repeat the process to see if it's enabled

I kindly ask for your help because I wonder if I report this to Wine devs who have no idea what all this mess is, they might tell me the bug comes from default MT5 and not Wine.

I'm also contacting metatrader team just in case.

**Comment by EarnForex** [comment]
> yes it's how i enable it each time, so there is a bug with wine

It looks like you are misunderstanding what I wrote. The settings in Tools->Options->Expert Advisors I was talking serve to disable autotrading on profile change. You should untick the respective box. Please see the attached screenshot.
![Screenshot 2023-10-20 105845](https://github.com/EarnForex/PositionSizer/assets/48102957/b616b7e6-a64b-4c9d-9692-1bead19717f7)

**Comment by BarbzYHOOL** [comment]
roflmao, thank you a lot (in fact mt5 support email doesn't exist, what a bad software)
It seems to work
This is the first time in my life that I've seen a software that auto-untick a box in settings after an action, so damn weird
And, I usually read all the stuff but dunno, it felt redundant so I never read those two lines (being forced to tick it everyday made me mad)

thanks a lot for saving me, sorry for bothering you

Also I have fixed another of your indicator that was not compiling, it's "risk calculator", I posted an issue about it, but I modified the dir structure so I don't think I should send the files. I think I've written in the issue how I fixed it
