### ISSUE TITLE
TP distance in points instead of a level not working properly

### ISSUE THREAD

**Issue by paymanz** [EarnForex/PositionSizer#78]
hi , when the option "TP distance in points instead of a level" is true i assume you should be able to change the TP by changing the point value number in the trading tab , but it still recognize the number as a level. can that be fixed please? thanks

**Comment by EarnForex** [comment]
Hello!

Could you please tell me more about how you get this issue? Are you on MT5 or MT4?

PS: If you are talking about the Trading tab, the TPs listed there are always in levels. If you want to see the point values, you can switch to the Main tab.

**Comment by paymanz** [comment]
> Hello!
> 
> Could you please tell me more about how you get this issue? Are you on MT5 or MT4?
> 
> PS: If you are talking about the Trading tab, the TPs listed there are always in levels. If you want to see the point values, you can switch to the Main tab.

ok the main tab does the trick. didnt know that,  thanks you
