### ISSUE TITLE
Risk of 1.5% displayed as 40%?????????

### ISSUE THREAD

**Issue by BarbzYHOOL** [EarnForex/PositionSizer#79]
I have three positions of 0.01 on XAUEUR, i made sure that each is around 0.5% risk
But when I look at the risk, it's all over the place, with a 40% risk

![image](https://github.com/EarnForex/PositionSizer/assets/29780637/f11e4b9a-e73c-4164-b091-d336eca23af2)
![image](https://github.com/EarnForex/PositionSizer/assets/29780637/47b0f352-c14c-4c07-a8b8-462110a484ac)
![image](https://github.com/EarnForex/PositionSizer/assets/29780637/3cf61a18-b531-4ef4-825d-6f2652abbf94)

I compared with the last two screenshots, to understand. and I don't know what is happening, my only guess is that it may only work with forex and not with other instruments

**Comment by EarnForex** [comment]
It looks like one of your XAUEUR trades is without a stop-loss. It's causing this issue.

PS: I recommend updating to 3.07.
