### ISSUE TITLE
Add fix SL and TP (using ATR) distance using previous candle options

### ISSUE THREAD

**Issue by Mukhalil01** [EarnForex/PositionSizer#80]
Hi,
Thank you for creating this amazing EA, current issues that I encountered is that, With ATR options, using previous candle for TP and SL, I find TP and SL move along with current price. kindly, please add set fix TP and SL distance using ATR  previous candle options, appreciate your help.

Regards 
Mok

**Comment by EarnForex** [comment]
Hello Mok,

Could you please elaborate? How would that work? What are ATR values would be added to or subtracted from if not from the current price?

**Comment by Mukhalil01** [comment]
> Hello Mok,
> 
> Could you please elaborate? How would that work? What are ATR values would be added to or subtracted from if not from the current price?

Ok, what I mean is the ATR values (Pips distance for TP and SL) added and subtracted from previous closed price candle. For example, if I go long, let say 30 pips (values from ATR calculations), TP will be 30 pips from previous closed price, not from current open price,  Hope this will clarify,  thank you

**Comment by EarnForex** [comment]
Then you need to set up a pending order with the Entry at the previous candle's close.

**Comment by Mukhalil01** [comment]
> Then you need to set up a pending order with the Entry at the previous candle's close.

I did try that, but then, I have to manually enter the price at  TP and SL box. Please correct me if I am wrong, thanks in advance

**Comment by EarnForex** [comment]
No, if you switch to Pending and move the Entry to your preferred level, the SL and TP lines will move with the Entry line as long as some ATR multipliers are given for them.

**Comment by Mukhalil01** [comment]
> No, if you switch to Pending and move the Entry to your preferred level, the SL and TP lines will move with the Entry line as long as some ATR multipliers are given for them.

Ok, I will try that after today's daily candle close, and revert to you later, thank you

**Comment by Mukhalil01** [comment]
> > No, if you switch to Pending and move the Entry to your preferred level, the SL and TP lines will move with the Entry line as long as some ATR multipliers are given for them.
> 
> Ok, I will try that after today's daily candle close, and revert to you later, thank you

I try using PO, unfortunately it enter into buy limit,  not instant. I also try to adjust TP and SL, using values from nnfx atr indicator, but the prices fluctuate, not fix as I expected. Kindly,  if possible,  for next update, if you can include, feature or option to set TP and SL (from ATR) from last day closed price, reason is most of the time, prices did not hit TP and reverse. Hope you can consider,  thanks

**Comment by EarnForex** [comment]
> I try using PO, unfortunately it enter into buy limit, not instant.

What do you mean? Were you expecting a pending order to be executed as a market order? Why would that happen?

> I also try to adjust TP and SL, using values from nnfx atr indicator, but the prices fluctuate, not fix as I expected.

Not sure what that means. Sorry!

> Kindly, if possible, for next update, if you can include, feature or option to set TP and SL (from ATR) from last day closed price, reason is most of the time, prices did not hit TP and reverse. Hope you can consider, thanks

It's still unclear to me how your proposal is supposed to work.
