### ISSUE TITLE
Wrong calculation of commission

### ISSUE THREAD

**Issue by dennysena** [EarnForex/PositionSizer#81]
![Screenshot (520)](https://github.com/EarnForex/PositionSizer/assets/154579042/e8ac766c-a6b2-4b55-82dd-0431dc69b49d)

As you can see in the result section my risk is 8.38 and my reward is 8.14.  That means the EA calculate my commission to be 0.24, right?
My broker charge $4 per lot and i know that i should enter half of it in the commission section because it is one way, so i enter $2.
The EA give the result of the position size 0.03 lot. Isn't my commission supposed to be 0.12 and my reward 8.26?

**Comment by EarnForex** [comment]
The commission is paid regardless of the trade's outcome. Both Reward and Risk include the commission. You Risk is calculated like this: (366 pips x 0.03 lot) + $0.12. Your Reward is calculated like this: (366 pips x 0.03 lot) - $0.12. Had there been no commission, the Risk would have been equal the Reward at 366 pips x 0.03 lot (considering that the position size would have remained the same, which isn't necessary the case).

**Comment by dennysena** [comment]
Thanks for explaining it to me and thanks a lot for this EA :)
