### ISSUE TITLE
Adding Stop-buy and Stop-sell entries

### ISSUE THREAD

**Issue by sepehrdaad** [EarnForex/PositionSizer#82]
Hi guys , Thank you so much for developing this EA ... It already solves so many problems for so many traders.

Since there is already stop-limit orders and if there are no technical complications, I was wondering if you could also include the buy stop and sell stop entries ... For many traders who would wanna enter the market as soon a particular high or low is taken , stop entry orders make all the difference because a lot of the times , we are not fast enough to press the market execution button in time . 

Thanks!

--Sepehrdad

**Comment by EarnForex** [comment]
Hello!

Stop orders (as well as limit orders) are already there. They are part of pending orders. Set the entry type to Pending and position the lines according to your requirements. That's it.
