### ISSUE TITLE
Problem selecting colours of the lines on MT5 for MACOS

### ISSUE THREAD

**Issue by maccieddu** [EarnForex/PositionSizer#83]
Good morning, in the Mac version of the expert position sizer it is not possible to change the basic colors of the various lines. The color picker doesn't appear and there isn't even a symbol to click on. Thank you for the work you do with this software.
![image](https://github.com/EarnForex/PositionSizer/assets/24259316/2135df89-730f-4432-a4b2-31f7a987ba93)

**Comment by EarnForex** [comment]
Hello!

The color picker doesn't work in MT5 under macOS. Your only option is to change the colors either via the .set file or directly in the source code.
