### ISSUE TITLE
Automatic breakeven pip calculator based on risk

### ISSUE THREAD

**Issue by tensopa** [EarnForex/PositionSizer#84]
At this point we have to manually enter the number of pips at which the stop loss goes breakeven. It would be nice if we could fill in the break-even point with the amount of risk. For example, I want my trade to go breakeven at a profit of 1R. The number of pips for 1R is always the same as the pip amount of the stop loss.

**Comment by EarnForex** [comment]
Not likely to get implemented in the Position Sizer.
