### ISSUE TITLE
SL not being applied in MT5

### ISSUE THREAD

**Issue by airKamTrader** [EarnForex/PositionSizer#85]
Hi Team

Post the recent update of MetaTrader 5, the SL entered in this tool is now frequently missing in the executed trade.

Many thanks
Kam

**Comment by airKamTrader** [comment]
I'm using version 3.07 of the Position Sizer. 

My MT 5 version is 5.00 build 4153 (22 Jan 2024).

Thanks
Kam

**Comment by EarnForex** [comment]
Hello!

What is the output in the Experts tab when you open a trade and this happens?
