### ISSUE TITLE
SL/Entry too close error (MT5)

### ISSUE THREAD

**Issue by airKamTrader** [EarnForex/PositionSizer#86]
Hi Team

Post the recent update of MetaTrader 5, I frequently get a "Too close!" error on my entered Stop-Loss and/or Entry preventing me from executing the trade.

It was fine pre the recent MetaTrader 5 update. 

I'm using version 3.07 of the Position Sizer. 

My MT 5 version is 5.00 build 4153 (22 Jan 2024).

Thanks
Kam

**Comment by EarnForex** [comment]
Hello!

This error usually means that the distance between the entered SL and the Entry level or between the Entry level and the current price (for pending orders) is less than the broker's mandated level.

**Comment by airKamTrader** [comment]
Thank you for your message. 

As you can see from the attachment, my SL is quite wide:

￼

**Comment by airKamTrader** [comment]
Actually I think my broker recently changed its min SL size. Please ignore this case. 

Thanks for your great work,
Kam
