### ISSUE TITLE
Possible bug when opening 2 same size positions in GER30 ( DAX ) 

### ISSUE THREAD

**Issue by xddbz** [EarnForex/PositionSizer#90]
Every once in a while when I try to open 2 positions that are the same size quickly at market it only opens the first one then I get a message that " adjust position size is less or equal to zero , not executing any trade " when It starts happening it doesn't go away no matter what I do. tried different demo account with different broker, closed all charts and re-opened and re-started the EA. I don't use any other expert and only use Moving average and candle timer indicator . it's really weird because it seems to work just fine until it doesn't and it only happens in GER30 index. the problem is only with same sized positions for example if I do 0.05 lot and 0.04 quickly it just works fine but same size positions only the first one opens .
![2024-04](https://github.com/EarnForex/PositionSizer/assets/13271728/9f4326f0-1bac-44db-8415-5462562e3120)

**Comment by EarnForex** [comment]
Hello!

Please look at your Trading tab. Most likely, there is some "max" setting that prevents opening another trade.

**Comment by xddbz** [comment]
> Hello!
> 
> Please look at your Trading tab. Most likely, there is some "max" setting that prevents opening another trade.

Hello , I checked the trading tab, all of them were set to 0. I think it has something to do with my custom chart when I reverted my chart to default it fixed it then reverted back to custom chart and it's still fixed so I think It has something to do with my chart. I think I just do that every once in a month that it happens, Anyway  thanks for this Amazing program works better than the paid ones on store it's simple and just works

**Comment by EarnForex** [comment]
Check also the checkboxes on the Trading tab:
Subtract open positions volume
Subtract pending orders volume

It could also be the case that you have a chart template that has those checkboxes ticked.

Anyway, whenever anything like this happens, you can also check the Experts tab of the Terminal subwindow for messages from the Position Sizer. It should mention what and why it calculated there.

**Comment by xddbz** [comment]
> Check also the checkboxes on the Trading tab: Subtract open positions volume Subtract pending orders volume
> 
> It could also be the case that you have a chart template that has those checkboxes ticked.
> 
> Anyway, whenever anything like this happens, you can also check the Experts tab of the Terminal subwindow for messages from the Position Sizer. It should mention what and why it calculated there.

it was totally it !!! 
"Subtract open positions volume" was checked, I think I accidently clicked it since I could enable it by clicking the text around the checkbox too and saved the chart as default . Thanks again
