### ISSUE TITLE
More Shortcuts

### ISSUE THREAD

**Issue by jeemitsha** [EarnForex/PositionSizer#95]
I wish to see more shortcuts for
BE
partials 25%
partials 50%
partials 75%

**Comment by jeemitsha** [comment]
i dont know how to implement it in this case, because there can be several trades open 
maybe thats the reason this is not avaliable

**Comment by jeemitsha** [comment]
you may just close this if this is the case

**Comment by EarnForex** [comment]
This is best solved with separate scripts.
