### ISSUE TITLE
Hide Lines

### ISSUE THREAD

**Issue by jeemitsha** [EarnForex/PositionSizer#96]
After a order is placed the lines should auto Hide so we get a sense of confirmation that the order got placed

**Comment by EarnForex** [comment]
Do you mean like automatically?

**Comment by jeemitsha** [comment]
yeah meaning after the order is placed, the lines should hide so we can see the order is placed and a sense of confirmation, what do you think ?

**Comment by EarnForex** [comment]
I see. I think it would be an overkill to add such a feature considering that the lines can now be hidden with a single click or with a single press of a key.

**Comment by jeemitsha** [comment]
ok
