### ISSUE TITLE
TP has weird values when set to zero

### ISSUE THREAD

**Issue by Waxavi** [EarnForex/PositionSizer#99]
When the TP is set to zero, and the TP Pips/Price hotkey is pressed, it returns some weird values

https://www.youtube.com/watch?v=jJDZGW3wyHI

**Comment by Waxavi** [comment]
[USDCAD133680729105445027.txt](https://github.com/user-attachments/files/16986597/USDCAD133680729105445027.txt)

Sample settings file if needed

**Comment by EarnForex** [comment]
Should be fixed in 3.10.
